spring.application.name=Employee


server.port=8020

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE

spring.datasource.username=mainuddin
spring.datasource.password=main123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
